#!/usr/bin/env bash
# SecondBrain end-to-end demo.
#
# Seeds a fresh DB with a realistic 8-capture workday, then exercises every
# user-facing command. Designed to be (a) honest — no LLM mocking, real
# pipeline; (b) deterministic — stub embedder so reruns produce stable output;
# (c) recordable — set `DEMO_RECORD=1` to write a markdown transcript to
# .demo/transcript.md.
#
# Run from the SecondBrain repo root:
#   ./demo.sh
#   DEMO_LLM=1 ./demo.sh                # also run digest --llm (needs Ollama)
#   DEMO_RECORD=1 ./demo.sh > /dev/null # write .demo/transcript.md

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DB_DIR="${ROOT}/.demo"
DB="${DB_DIR}/secondbrain.db"
PY="${ROOT}/.venv/bin/python"
SECONDBRAIN="${ROOT}/.venv/bin/secondbrain"
TRANSCRIPT="${ROOT}/.demo/transcript.md"

if [[ ! -x "$PY" ]]; then
  echo "no venv — run: python3 -m venv .venv && .venv/bin/pip install -e '.[dev]'" >&2
  exit 1
fi

# Clean slate so the demo is deterministic.
rm -rf "$DB_DIR"
mkdir -p "$DB_DIR"

record() {
  if [[ "${DEMO_RECORD:-0}" == "1" ]]; then
    echo "$@" >> "$TRANSCRIPT"
  fi
  echo "$@"
}

run_cmd() {
  local label="$1"; shift
  record ""
  record "### \$ $label"
  record '```'
  if [[ "${DEMO_RECORD:-0}" == "1" ]]; then
    "$@" 2>&1 | tee -a "$TRANSCRIPT"
  else
    "$@" 2>&1
  fi
  record '```'
}

if [[ "${DEMO_RECORD:-0}" == "1" ]]; then
  mkdir -p "$(dirname "$TRANSCRIPT")"
  cat > "$TRANSCRIPT" <<EOF
# SecondBrain end-to-end demo run

> Generated by \`demo.sh\` on $(date -u +'%Y-%m-%d %H:%M:%S UTC').
> Reproducible: \`DEMO_RECORD=1 ./demo.sh\`.

This is a real run of the shipping CLI against a fresh database. No mocking.
The 8 captures below are seeded directly into the OLTP store; they represent
a typical workday's worth of screen-context the daemon would have written
if you'd run \`secondbrain run\` for an hour.
EOF
fi

echo ""
echo "=== 1. Seeding a realistic 8-capture workday ==="

"$PY" <<'PYEOF'
from datetime import datetime, timedelta, timezone
from pathlib import Path

from secondbrain.embed.stub import StubEmbedder
from secondbrain.indexing import Indexer
from secondbrain.memory.amem import AMemLinker
from secondbrain.memory.entities import EntityResolver
from secondbrain.memory.pipeline import MemoryPipeline
from secondbrain.models import Capture
from secondbrain.store.captures import insert as insert_capture
from secondbrain.store.kg import KnowledgeGraph
from secondbrain.store.oltp import open_unencrypted
from secondbrain.store.text_index import TextIndex
from secondbrain.store.vector import VectorStore

ROOT = Path(__file__).resolve().parent if "__file__" in dir() else Path.cwd()
BASE = Path(".demo")

oltp = open_unencrypted(BASE / "secondbrain.db")
vector = VectorStore(db_path=BASE / "lance")
text = TextIndex(index_path=BASE / "tantivy")
kg = KnowledgeGraph(db_path=BASE / "kg")
embedder = StubEmbedder()
indexer = Indexer(embedder=embedder, vector=vector, text=text)
pipe = MemoryPipeline(
    kg=kg,
    linker=AMemLinker(embedder=embedder),
    resolver=EntityResolver(kg=kg),
)

day = datetime(2026, 5, 12, 9, 0, tzinfo=timezone.utc)
fixtures = [
    ("Slack",   "Sam Reed: I'll send the Snowflake migration design doc by Friday."),
    ("Linear",  "Pat Lane updated stripe-billing-hotfix: token expiry fix shipped, rollout pushed to Tuesday for safety."),
    ("Notion",  "Q3 budget review meeting outcomes — Snowflake spend stays at $48k/mo; BigQuery costed at $42k/mo for parity."),
    ("Datadog", "Kafka consumer lag spiked at 14:02 on the ingest-prod-2 pipeline; pager fired; resolved 14:09."),
    ("Slack",   "Alex Kim hiring panel feedback — 4 of 5 say strong hire for the engineering manager role."),
    ("Notion",  "Pat Lane will own the rollback plan for the Snowflake migration; new owner of migration is Pat."),
    ("Linear",  "Pat Lane: I will deploy the Stripe billing rollback on Wednesday afternoon."),
    ("Notes",   "Weekend hike — golden gate trail conditions are dry; 8.4 mi."),
]
for i, (app, ax_text) in enumerate(fixtures):
    cap = Capture(
        id=f"demo-{i:02d}",
        captured_at=day + timedelta(minutes=15 * i),
        app_name=app,
        app_bundle_id=f"com.example.{app.lower()}",
        ax_text=ax_text,
    )
    insert_capture(oltp, cap)
    indexer.index_capture(cap)
    pipe.ingest(cap)
oltp.close()
print(f"  seeded: 8 captures across {len(set(f[0] for f in fixtures))} apps")
PYEOF

run_cmd "secondbrain status --no-encryption --db .demo/secondbrain.db" \
  "$SECONDBRAIN" status --no-encryption --db "$DB"

run_cmd "secondbrain search 'snowflake quarterly review' --no-encryption --stub-embedder --db .demo/secondbrain.db" \
  "$SECONDBRAIN" search "snowflake quarterly review" --no-encryption --stub-embedder --db "$DB"

run_cmd "secondbrain search 'kafka pipeline lag' --no-encryption --stub-embedder --db .demo/secondbrain.db" \
  "$SECONDBRAIN" search "kafka pipeline lag" --no-encryption --stub-embedder --db "$DB"

run_cmd "secondbrain who 'Pat Lane' --db .demo/secondbrain.db" \
  "$SECONDBRAIN" who "Pat Lane" --db "$DB"

run_cmd "secondbrain who 'Sam Reed' --db .demo/secondbrain.db" \
  "$SECONDBRAIN" who "Sam Reed" --db "$DB"

run_cmd "secondbrain digest --period day --day 2026-05-12 --db .demo/secondbrain.db" \
  "$SECONDBRAIN" digest --period day --day 2026-05-12 --db "$DB"

if [[ "${DEMO_LLM:-0}" == "1" ]]; then
  run_cmd "secondbrain digest --period day --day 2026-05-12 --llm --llm-model gpt-oss:20b-cloud --db .demo/secondbrain.db" \
    "$SECONDBRAIN" digest --period day --day 2026-05-12 --llm \
    --llm-model gpt-oss:20b-cloud --db "$DB"
fi

# Show the MCP server is wirable.
run_cmd "secondbrain mcp-doctor --db .demo/secondbrain.db" \
  "$SECONDBRAIN" mcp-doctor --db "$DB"

# Prove the GDPR delete cascades.
run_cmd "secondbrain forget --no-encryption --db .demo/secondbrain.db --capture-id demo-04 --reason 'demo cascade'" \
  "$SECONDBRAIN" forget --no-encryption --db "$DB" --capture-id demo-04 --reason "demo cascade"

run_cmd "secondbrain who 'Alex Kim' --db .demo/secondbrain.db   # should now return (no memories)" \
  "$SECONDBRAIN" who "Alex Kim" --db "$DB" || true

if [[ "${DEMO_RECORD:-0}" == "1" ]]; then
  echo ""
  echo "transcript written to $TRANSCRIPT"
fi
